default_context:
  project_name: 'Lost Item Manager'
  project_slug: 'lost-item-manager'
  domain_main: 'lost-item-manager.com'
  domain_staging: 'stag.lost-item-manager.com'
  docker_swarm_stack_name_main: 'lost-item-manager-com'
  docker_swarm_stack_name_staging: 'stag-lost-item-manager-com'
  secret_key: '477d244c99846476e9f0c449105b306cef5055158cc57f9eab97e637b506584d'
  first_superuser: 'admin@lost-item-manager.com'
  first_superuser_password: 'password'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.lost-item-manager.com, https://stag.lost-item-manager.com, https://lost-item-manager.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@lost-item-manager.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@lost-item-manager.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'lost-item-manager.com'
  traefik_constraint_tag_staging: 'stag.lost-item-manager.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
