"""add image_url to item

Revision ID: a76231157912
Revises: 79841c9967f4
Create Date: 2020-04-14 06:42:45.205459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76231157912'
down_revision = '79841c9967f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_url')
    # ### end Alembic commands ###
